name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: nubjs/setup-nub@v0
        with:
          cache: true
      - run: nub install --frozen-lockfile
      - run: nubx biome ci src tests
      - run: nub run build
      - run: nub run test
